apiVersion: v1
kind: Secret
metadata:
  name: ms-support-hosts-secrets
  labels:
    app.kubernetes.io/component: ms-support-hosts-secrets
    {{- include "support.labels" . | nindent 4}}
type: Opaque
data:
  messages_host: {{ .Values.messagesHost | b64enc }}
  users_host: {{ .Values.usersHost | b64enc }}
  songs_host: {{ .Values.songsHost | b64enc }}