apiVersion: v1
kind: Secret
metadata:
  name: ms-support-jwt-secrets
  labels:
    app.kubernetes.io/component: ms-support-jwt-secrets
    {{- include "support.labels" . | nindent 4 }}
type: Opaque
data:
  jwt_secret: {{ .Values.jwtSecret | b64enc }}