apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  labels: 
    app.kubernetes.io/component: mongodb
    {{- include "support.labels" . | nindent 4 }}
type: Opaque
data:
  support_db_url: {{ .Values.supportMongoUrl | b64enc }}