apiVersion: v1
kind: Secret
metadata:
  name: sendgrid
  labels: 
    app.kubernetes.io/component: sendgrid
    {{- include "support.labels" . | nindent 4 }}
type: Opaque
data:
  sendgrid_api_key: {{ .Values.supportSendgridApiKey | b64enc }}