components:
  securitySchemes:
    bearerAuth:           
      type: http
      scheme: bearer
      bearerFormat: JWT    
      description: >-
        Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".

security:
  - bearerAuth: []  